# Generated by Django 4.1.7 on 2023-04-01 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_session_status_alter_session_type'),
    ]

    operations = [
        migrations.RunSQL('DROP TABLE home_session_members;'),
    ]
