# Generated by Django 4.1.7 on 2023-03-31 11:27

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_invites_received_customuser_invites_sent'),
        ('home', '0009_alter_session_status_alter_session_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionMember',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('debt', models.FloatField(default=0)),
                ('settled_sum', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='members',
            field=models.ManyToManyField(help_text='Add members to this session', to='home.sessionmember'),
        ),
    ]
