# Generated by Django 4.1.7 on 2023-04-01 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_session_status_alter_session_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.FloatField(default=0)),
                ('settled_sum', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='parent_club',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='home.club'),
        ),
        migrations.AlterField(
            model_name='session',
            name='members',
            field=models.ManyToManyField(help_text='Add members to this session', to='home.sessionmember'),
        ),
    ]
