# Generated by Django 4.1.7 on 2023-04-01 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_delete_home_session_members'),
        ('home', '0011_sessionmember_session_parent_club_and_more'),
    ]

    operations = [
    ]
