# Generated by Django 4.1.7 on 2023-03-31 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_debt_sessionmember_debit'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='parent_club',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='home.club'),
        ),
    ]
