# Generated by Django 4.1.7 on 2023-03-31 18:09

from django.db import migrations, models


def set_default_sessionmember_id(apps, schema_editor):
    SessionMember = apps.get_model('home', 'SessionMember')
    for session_member in SessionMember.objects.all():
        session_member.id = session_member.pk
        session_member.save()


class Migration(migrations.Migration):

    dependencies = [
        ('home', 'sessionmember_alter_session_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmember',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RunPython(set_default_sessionmember_id),
        migrations.AlterField(
            model_name='sessionmember',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
