# Generated by Django 4.1.7 on 2023-04-01 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_members_session_membr_sessionmember_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='membr',
        ),
    ]
