# Generated by Django 4.1.7 on 2023-04-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_session_membr'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='member',
            field=models.ManyToManyField(help_text='Add members to this session', to='home.sessionmember'),
        ),
    ]
