# Generated by Django 4.1.7 on 2023-03-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_invite_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'open'), ('c', 'closed')], default='o', help_text='Status of the session', max_length=1),
        ),
        migrations.AlterField(
            model_name='session',
            name='type',
            field=models.CharField(blank=True, choices=[('z', 'Zero Sum'), ('s', 'Split Sum')], default='z', help_text='Type of session', max_length=1),
        ),
    ]
