from django.urls import path, include
from . import views

app_name = 'home'
urlpatterns = [    
    path('', views.index, name='index'),
    path('accounts/', include('allauth.urls')),
    path('home', views.index, name='index2'),
    path('myclubs/', views.myclublist_view, name='myclubs'),   
    path('myinvites/', views.myinvites_list, name='myinvites'),
    path('mydebit/<str:interval>', views.mysums, name='mysums'), 
    path('mydebit/create-live-session', views.create_live_session, name='create-live-session'),
    path('mydebit/live-session-detail/<str:pk>', views.livesession_detail, name='live-session-detail'),
    path('mydebit/live-session-detail/<str:lspk>/plus-buy-in', views.plus_buy_in, name='plus-buy-in'),
    path('mydebit/live-session-detail/<str:lspk>/plus-stack', views.plus_stack, name='plus-stack'),
    path('clubs/', views.ClubListView.as_view(), name='clubs'),
    path('club/<str:pk>', views.ClubDetailView.as_view(), name='club-detail'),
    path('session/<str:pk>', views.SessionDetailView.as_view(), name='session-detail'),
    path('clubs/create/', views.ClubCreate.as_view(), name='club-create'),
    path('club/<int:pk>/update', views.ClubUpdate.as_view(), name='club-update'),
    path('club/<int:pk>/delete', views.ClubDelete.as_view(), name='club-delete'),
    path('club/<int:pk>/invite', views.club_invite, name='club-invite'),
    path('club/<int:pk>/join-requests', views.club_join_requests, name='club-join-requests'),
    path('club/<int:pk>/request-to-join', views.club_request_join, name='club-request-to-join'),        
    path('club/<int:pk>/accept-join-request', views.accept_join_request, name='accept-club-join-request'),
    path('club/<int:pk>/create-session', views.create_session, name='club-create-session'),    
    path('test', views.test_view, name='test'),
    path('accept_invite/<str:pk>', views.accept_invite, name='accept-invite'),
    path('session/<str:pk>/adduser', views.session_add_user, name='session-add-user'),
    path('session/<str:pk>/make-payments', views.make_payments, name='make-payments'),
    path('session/<str:pk>/settle', views.settle_session, name='settle-session'),
    path('club/session/<str:pk>/delete', views.delete_session, name='delete-session'),
    path('session/<str:spk>/<str:mpk>/debit', views.add_member_debit, name='add-member-debit'),
    path('session/<str:spk>/<str:mpk>/remove', views.remove_session_member, name='remove-session-member'),   
    path('session/<str:spk>/<str:mpk>/plus-debit', views.plus_debit, name='plus-debit'),
    path('session/payment/<str:pk>/pay', views.pay_payment, name='pay-payment'),  
    path('session/payment/<str:pk>/unpay', views.unpay_payment, name='unpay-payment'),
    path('mydebit/payment/<str:pk>/pay', views.pay_payment, name='pay-payment'),  
    path('mydebit/payment/<str:pk>/unpay', views.unpay_payment, name='unpay-payment'),  
    path('session/sum/<str:pk>/pay', views.pay_payment, name='pay-sum'),  
    path('session/sum/<str:pk>/unpay', views.unpay_sum, name='unpay-sum'),
    path('mydebit/sum/<str:pk>/pay', views.pay_sum, name='pay-sum'),  
    path('mydebit/sum/<str:pk>/unpay', views.unpay_sum, name='unpay-sum'),  
]