# Generated by Django 4.1.7 on 2023-04-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_club_invites_sent_club_sessions'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='clubs',
            field=models.ManyToManyField(help_text='Clubs this user is associated with', to='home.club'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='invites_received',
            field=models.ManyToManyField(help_text='Invites received by this user', related_name='invites_received', to='home.invite'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='invites_sent',
            field=models.ManyToManyField(help_text='Invites sent by this user', related_name='invites_sent', to='home.invite'),
        ),
    ]
