# Generated by Django 4.1.7 on 2023-02-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_club_members_alter_club_owner_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='clubs',
            field=models.ManyToManyField(help_text='Clubs this user is associated with', to='home.club'),
        ),
    ]
