# Generated by Django 4.1.5 on 2023-04-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_sessionmember_main_account_alter_session_name_sum_and_more'),
        ('accounts', '0002_customuser_clubs_customuser_invites_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sums',
            field=models.ManyToManyField(help_text='Sums assinged to this user', to='home.sum'),
        ),
    ]
