# Generated by Django 4.1.7 on 2023-04-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser__sums'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='_sums',
            new_name='sums',
        ),
    ]
