# Generated by Django 4.1.7 on 2023-05-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_payment_options_joinrequest_club_join_requests'),
        ('accounts', '0005_customuser_payments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['username']},
        ),
        migrations.AddField(
            model_name='customuser',
            name='join_requests',
            field=models.ManyToManyField(to='home.joinrequest'),
        ),
    ]
