# Generated by Django 4.2.3 on 2023-07-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_livesession_stackdelta_livesession_stack_delta'),
        ('accounts', '0006_alter_customuser_options_customuser_join_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='livesessions',
            field=models.ManyToManyField(help_text='Payments involving this user', to='home.livesession'),
        ),
    ]
