# Generated by Django 4.1.7 on 2023-07-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_livesession_stackdelta_livesession_stack_delta'),
        ('accounts', '0007_customuser_livesessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='livesessions',
            field=models.ManyToManyField(help_text='livesessions', to='home.livesession'),
        ),
    ]
