# Generated by Django 4.1.7 on 2023-02-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='sessions',
            field=models.ManyToManyField(to='home.session'),
        ),
    ]
