# Generated by Django 4.1.7 on 2023-04-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_invite'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Member', max_length=200)),
                ('debit', models.FloatField(default=0)),
                ('settled_sum', models.FloatField(default=0)),
            ],
        ),
    ]
