# Generated by Django 4.1.7 on 2023-02-15 17:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_alter_club_members_alter_club_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='time_created',
            field=models.DateField(default=datetime.datetime(2023, 2, 15, 17, 10, 34, 783725, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular invite', primary_key=True, serialize=False)),
                ('time_created', models.DateField(default=datetime.datetime(2023, 2, 15, 17, 10, 34, 784726, tzinfo=datetime.timezone.utc))),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.club')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
