# Generated by Django 4.1.7 on 2023-04-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='invites_sent',
            field=models.ManyToManyField(to='home.invite'),
        ),
        migrations.AddField(
            model_name='club',
            name='sessions',
            field=models.ManyToManyField(to='home.session'),
        ),
    ]
