# Generated by Django 4.1.7 on 2023-02-15 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_club_time_created_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='time_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invite',
            name='time_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
