# Generated by Django 4.1.7 on 2023-04-01 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_session_parent_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmember',
            name='parent_session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.session'),
        ),
    ]
