# Generated by Django 4.1.7 on 2023-04-01 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_sessionmember_parent_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='member',
            new_name='members',
        ),
    ]
