# Generated by Django 4.1.7 on 2023-04-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_sessionmember_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionmember',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
