# Generated by Django 4.1.5 on 2023-04-10 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_sessionmember_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='parent_club',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.club'),
        ),
    ]
