# Generated by Django 4.1.7 on 2023-04-23 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_alter_session_parent_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(default='<django.db.models.fields.DateField>', max_length=200),
        ),
        migrations.CreateModel(
            name='Sum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular sum across whole sums list', primary_key=True, serialize=False)),
                ('current_sum', models.FloatField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('member', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_session', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.session')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='sums',
            field=models.ManyToManyField(to='home.sum'),
        ),
    ]
