# Generated by Django 4.1.5 on 2023-04-26 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_sessionmember_main_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invite',
            options={'ordering': ['-time_created']},
        ),
    ]
