# Generated by Django 4.1.7 on 2023-04-27 06:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_sum_partial_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sum',
            options={'ordering': ['-time_created']},
        ),
        migrations.AddField(
            model_name='sum',
            name='time_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
