# Generated by Django 4.1.7 on 2023-04-30 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0017_alter_sum_options_sum_time_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sum',
            name='partial_paid',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular sum across whole sums list', primary_key=True, serialize=False)),
                ('paid', models.BooleanField(default=False)),
                ('time_created', models.DateField(default=django.utils.timezone.now)),
                ('from_member', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='from_member', to=settings.AUTH_USER_MODEL)),
                ('parent_session', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.session')),
                ('to_member', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='to_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_created'],
            },
        ),
    ]
