# Generated by Django 4.1.7 on 2023-05-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_sum_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='payments',
            field=models.ManyToManyField(to='home.payment'),
        ),
    ]
