# Generated by Django 4.1.7 on 2023-05-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_session_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
