# Generated by Django 4.1.7 on 2023-05-02 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0022_session_bias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular invite', primary_key=True, serialize=False)),
                ('time_created', models.DateField(default=django.utils.timezone.now)),
                ('accepted', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Join_request_for_user', to=settings.AUTH_USER_MODEL)),
                ('parent_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.club')),
            ],
            options={
                'ordering': ['-time_created'],
            },
        ),
        migrations.AddField(
            model_name='club',
            name='join_requests',
            field=models.ManyToManyField(to='home.joinrequest'),
        ),
    ]
