# Generated by Django 4.2.3 on 2023-08-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_rename_result_sum_livesession_stack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livesession',
            options={'ordering': ['-date']},
        ),
    ]
