# Generated by Django 4.1.7 on 2023-02-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_club_time_created_alter_invite_time_created'),
        ('accounts', '0002_customuser_clubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='invites_received',
            field=models.ManyToManyField(help_text='Invites received by this user', related_name='invites_received', to='home.invite'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='invites_sent',
            field=models.ManyToManyField(help_text='Invites sent by this user', related_name='invites_sent', to='home.invite'),
        ),
    ]
